version: '3.3'

services:
  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=inventory
      - MYSQL_USER=debezium
      - MYSQL_PASSWORD=debezium
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/inventory.sql:/home/inventory.sql

  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.3
    ports:
      - "0.0.0.0:2181:2181"
      - "0.0.0.0:2888:2888"
      - "0.0.0.0:3888:3888"

  kafka:
    container_name: kafka
    image: debezium/kafka:1.3
    ports:
      - "0.0.0.0:9092:9092"
    links:
      - zookeeper
    environment: 
      - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    container_name: connect_a
    image: debezium/connect:1.3
    ports:
      - "0.0.0.0:8083:8083"
      - "0.0.0.0:5005:5005"
    links:
      - kafka
      - mysql_db
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
